// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eweqq7h9oPPXmhNg71Z2fg
// Component: T3xw65d63J

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import YouTube from "@plasmicpkgs/react-youtube"; // plasmic-import: CHO21V9uYw/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import * as plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import * as projectcss from "./plasmic_revnitro.module.css"; // plasmic-import: eweqq7h9oPPXmhNg71Z2fg/projectcss
import * as sty from "./PlasmicBlogCard2.module.css"; // plasmic-import: T3xw65d63J/css

createPlasmicElementProxy;

export type PlasmicBlogCard2__VariantMembers = {};
export type PlasmicBlogCard2__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlogCard2__VariantsArgs;
export const PlasmicBlogCard2__VariantProps = new Array<VariantPropType>();

export type PlasmicBlogCard2__ArgsType = {};
type ArgPropType = keyof PlasmicBlogCard2__ArgsType;
export const PlasmicBlogCard2__ArgProps = new Array<ArgPropType>();

export type PlasmicBlogCard2__OverridesType = {
  root?: p.Flex<"div">;
  cards1?: p.Flex<"div">;
  content?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  youTube?: p.Flex<typeof YouTube>;
  badgesNeutral?: p.Flex<"div">;
  title?: p.Flex<"div">;
};

export interface DefaultBlogCard2Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicBlogCard2__RenderFunc(props: {
  variants: PlasmicBlogCard2__VariantsArgs;
  args: PlasmicBlogCard2__ArgsType;
  overrides: PlasmicBlogCard2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"cards1"}
        data-plasmic-override={overrides.cards1}
        className={classNames(projectcss.all, sty.cards1)}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"content"}
          data-plasmic-override={overrides.content}
          hasGap={true}
          className={classNames(projectcss.all, sty.content)}
        >
          {true ? (
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <YouTube
                data-plasmic-name={"youTube"}
                data-plasmic-override={overrides.youTube}
                className={classNames("__wab_instance", sty.youTube)}
                fs={true}
                modestbranding={true}
                playsinline={true}
                rel={true}
                videoId={"SyTqxVzN1hw" as const}
              />
            </div>
          ) : null}
          <p.Stack
            as={"div"}
            data-plasmic-name={"badgesNeutral"}
            data-plasmic-override={overrides.badgesNeutral}
            hasGap={true}
            className={classNames(projectcss.all, sty.badgesNeutral)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4HZol
              )}
            >
              {"CAR"}
            </div>
          </p.Stack>
          <div
            data-plasmic-name={"title"}
            data-plasmic-override={overrides.title}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.title
            )}
          >
            {"Engine & Strong Hybrid Explained"}
          </div>
          {false ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uqp2
              )}
            >
              {
                "This is a description of the text that is in the article as a pre screener for what you need to know."
              }
            </div>
          ) : null}
        </p.Stack>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "cards1",
    "content",
    "freeBox",
    "youTube",
    "badgesNeutral",
    "title"
  ],
  cards1: ["cards1", "content", "freeBox", "youTube", "badgesNeutral", "title"],
  content: ["content", "freeBox", "youTube", "badgesNeutral", "title"],
  freeBox: ["freeBox", "youTube"],
  youTube: ["youTube"],
  badgesNeutral: ["badgesNeutral"],
  title: ["title"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  cards1: "div";
  content: "div";
  freeBox: "div";
  youTube: typeof YouTube;
  badgesNeutral: "div";
  title: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlogCard2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlogCard2__VariantsArgs;
    args?: PlasmicBlogCard2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlogCard2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlogCard2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlogCard2__ArgProps,
          internalVariantPropNames: PlasmicBlogCard2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBlogCard2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogCard2";
  } else {
    func.displayName = `PlasmicBlogCard2.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogCard2 = Object.assign(
  // Top-level PlasmicBlogCard2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cards1: makeNodeComponent("cards1"),
    content: makeNodeComponent("content"),
    freeBox: makeNodeComponent("freeBox"),
    youTube: makeNodeComponent("youTube"),
    badgesNeutral: makeNodeComponent("badgesNeutral"),
    title: makeNodeComponent("title"),

    // Metadata about props expected for PlasmicBlogCard2
    internalVariantProps: PlasmicBlogCard2__VariantProps,
    internalArgProps: PlasmicBlogCard2__ArgProps
  }
);

export default PlasmicBlogCard2;
/* prettier-ignore-end */
